### ISSUE TITLE
DeviceAlreadyExists error

### ISSUE THREAD

**Issue by mikery** [tschellenbach/Snaptastic#11]
When a device already exists, we should log a warning and proceed. Or make this behaviour optional.

Use case: snaptatic fails for some reason, and only half of the required volumes are mounted. You want to run snaptastic again to mount the rest of the volumes, but you don't want to wait ages for the already-attached ones to be detached.

**Comment by tschellenbach** [comment]
Optional seems to make most sense, as it's used for manual intervention.
If it encounters this during other circumstances something clearly went wrong :)
