### ISSUE TITLE
mount not ready snapshot

### ISSUE THREAD

**Issue by tbarbugli** [tschellenbach/Snaptastic#12]
snaptastic mount-snapshots x should fail loudly if the snapshot is not 100% ready (instead of try for 45 secs and then timeout)

**Comment by mikery** [comment]
It already raises an exception, which is pretty loud.

I'm going to increase the timeout, 45 seconds is way too short.

**Comment by tbarbugli** [comment]
going to try and replicate this again, i might be wrong but it was timing out and the only snapshot was not 100% done.

**Comment by mikery** [comment]
Ah, I see what you mean. The snapshot is not in the 'completed' state, so it can't be mounted.

We need to either…
- fail loudly at this point (the current behavior)
- poll until the snapshot is ready, then try again

Another 'configurable behavior' thing.
